let users = [
  {
    id: 1,
    name: "Muhammadamin",
    age: 18,
    adress: "Fergana",
    instagram:
      "https://www.instagram.com/muhammadamin_29___?igsh=anAyZGw0ZTJrdzdj&utm_source=qr",
    telegram: "https://t.me/wewkenss",
    githup: "https://github.com/milano-orgi",
  },
  {
    id: 2,
    name: "Abdulloh",
    age: 18,
    adress: "Namangan",
    instagram:
      "https://www.instagram.com/abdulloh_2005_/?igsh=MzRlODBiNWY3Yw==",
    telegram: "https://t.me/Abdulloh_2005",
    githup: "https://github.com/abdulloh2005",
  },
  {
    id: 3,
    name: "Sardor",
    age: 18,
    adress: "Andijon",
    instagram: "https://www.instagram.com/sardor_2005_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/sardor_2005",
    githup: "https://github.com/sardor2005",
  },
  {
    id: 4,
    name: "Hasan",
    age: 21,
    adress: "Bukhara",
    instagram: "https://www.instagram.com/hasan_2002_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/hasan_2002",
    githup: "https://github.com/hasan2002",
  },
  {
    id: 5,
    name: "Husan",
    age: 22,
    adress: "Khiva",
    instagram: "https://www.instagram.com/husan_2001_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/husan_2001",
    githup: "https://github.com/husan2001",
  },
  {
    id: 6,
    name: "Ali",
    age: 23,
    adress: "Andijan",
    instagram: "https://www.instagram.com/olim_2000_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/olim_2000",
    githup: "https://github.com/olim2000",
  },
  {
    id: 7,
    name: "Anvar",
    age: 21,
    adress: "Andijan",
    instagram: "https://www.instagram.com/olim_2000_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/olim_2000",
    githup: "https://github.com/olim2000",
  },
  {
    id: 8,
    name: "Aqlvoy",
    age: 12,
    adress: "Andijan",
    instagram: "https://www.instagram.com/olim_2000_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/olim_2000",
    githup: "https://github.com/olim2000",
  },
  {
    id: 9,
    name: "Bilmasvoy",
    age: 15,
    adress: "Andijan",
    instagram: "https://www.instagram.com/olim_2000_/?igsh=Y2Y0ZjI3Y2E3Yg==",
    telegram: "https://t.me/olim_2000",
    githup: "https://github.com/olim2000",
  },
];

export default users;
